# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-13 15:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='组名')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_leader', to=settings.AUTH_USER_MODEL, verbose_name='小组组长')),
                ('members', models.ManyToManyField(blank=True, null=True, related_name='user_groups', to=settings.AUTH_USER_MODEL, verbose_name='小组成员')),
            ],
            options={
                'verbose_name_plural': '小组',
                'verbose_name': '小组',
            },
        ),
    ]
