# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-13 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20180313_1536'),
        ('users', '0003_auto_20180312_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='leader',
        ),
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
