# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-15 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psp', models.IntegerField(default=0, verbose_name='个人sp值')),
                ('create', models.DateField(auto_now_add=True, verbose_name='任务创建时间')),
            ],
            options={
                'verbose_name_plural': '个人任务',
                'verbose_name': '个人任务',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('create', models.DateField(auto_now_add=True, verbose_name='项目创建时间')),
                ('start_time', models.DateField(blank=True, null=True, verbose_name='项目开始时间')),
                ('end_time', models.DateField(blank=True, null=True, verbose_name='项目终止时间')),
                ('executing', models.IntegerField(default=0, verbose_name='项目执行时间')),
                ('acceptance', models.IntegerField(default=0, verbose_name='项目验收时间')),
                ('sp', models.IntegerField(default=0, verbose_name='项目SP值')),
                ('weight', models.FloatField(default=1.0, verbose_name='项目权重')),
                ('impression', models.FloatField(default=0, verbose_name='项目成效')),
                ('acceptance_serious_bug', models.IntegerField(default=0, verbose_name='验收阶段严重缺陷')),
                ('acceptance_medium_bug', models.IntegerField(default=0, verbose_name='验收阶段中级缺陷')),
                ('acceptance_slight_bug', models.IntegerField(default=0, verbose_name='验收阶段低级缺陷')),
                ('release_serious_bug', models.IntegerField(default=0, verbose_name='发布阶段严重缺陷')),
                ('release_medium_bug', models.IntegerField(default=0, verbose_name='发布阶段中级缺陷')),
                ('release_slight_bug', models.IntegerField(default=0, verbose_name='发布阶段低级缺陷')),
                ('status', models.CharField(choices=[('executing', '执行'), ('acceptance', '验收'), ('release', '发布')], default='executing', max_length=15)),
            ],
            options={
                'verbose_name_plural': '项目',
                'verbose_name': '项目',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('executing', '执行'), ('acceptance', '验收'), ('release', '发布')], default='executing', max_length=15)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('gsp', models.IntegerField(default=0, verbose_name='小组SP值')),
                ('create', models.DateField(auto_now_add=True, verbose_name='任务创建时间')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_task', to='group.Group', verbose_name='任务参与团队')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_task', to='project.Project', verbose_name='项目')),
            ],
            options={
                'verbose_name_plural': '小组任务',
                'verbose_name': '小组任务',
            },
        ),
    ]
