# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-12 15:51
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('create_time', models.DateField(default=datetime.datetime.now, verbose_name='项目创建时间')),
                ('start_time', models.DateField(blank=True, null=True, verbose_name='项目开始时间')),
                ('end_time', models.DateField(blank=True, null=True, verbose_name='项目结束时间')),
                ('acceptance_time', models.DateField(blank=True, null=True, verbose_name='项目验收时间')),
                ('sp', models.IntegerField(default=0, verbose_name='项目SP值')),
                ('weight', models.FloatField(default=1.0, verbose_name='项目权重')),
                ('impression', models.FloatField(blank=True, null=True, verbose_name='项目成效')),
                ('acceptance_serious_bug', models.IntegerField(blank=True, default=0, null=True, verbose_name='验收阶段严重缺陷')),
                ('acceptance_medium_bug', models.IntegerField(blank=True, default=0, null=True, verbose_name='验收阶段中级缺陷')),
                ('acceptance_slight_bug', models.IntegerField(blank=True, default=0, null=True, verbose_name='验收阶段低级缺陷')),
                ('release_serious_bug', models.IntegerField(blank=True, default=0, null=True, verbose_name='发布阶段严重缺陷')),
                ('release_medium_bug', models.IntegerField(blank=True, default=0, null=True, verbose_name='发布阶段中级缺陷')),
                ('release_slight_bug', models.IntegerField(blank=True, default=0, null=True, verbose_name='发布阶段低级缺陷')),
                ('status', models.CharField(choices=[('executing', '执行'), ('acceptance', '验收'), ('release', '发布')], default='executing', max_length=15)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_projects', to=settings.AUTH_USER_MODEL, verbose_name='项目经理')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('executing', '执行'), ('acceptance', '验收'), ('release', '发布')], default='executing', max_length=15)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('GSP', models.IntegerField(default=0, verbose_name='部门SP值')),
                ('group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_task', to='users.Group', verbose_name='任务参与团队')),
                ('members', models.ManyToManyField(blank=True, null=True, related_name='user_tasks', to=settings.AUTH_USER_MODEL, verbose_name='任务参与人员')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_task', to='project.Project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
            },
        ),
    ]
