# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-12 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='acceptance_time',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_time',
        ),
        migrations.AddField(
            model_name='project',
            name='acceptance',
            field=models.IntegerField(default=0, verbose_name='项目验收时间'),
        ),
        migrations.AddField(
            model_name='project',
            name='executing',
            field=models.IntegerField(default=0, verbose_name='项目执行时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_time',
            field=models.DateField(blank=True, null=True, verbose_name='项目终止时间'),
        ),
    ]
