# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-12 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20180312_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='GSP',
            new_name='gsp',
        ),
    ]
