# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-17 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20180315_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='persontask',
            name='status',
            field=models.CharField(choices=[('executing', '执行'), ('acceptance', '验收'), ('release', '发布')], default='executing', max_length=15),
        ),
    ]
