# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-21 12:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_persontask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_time',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2018, 3, 21, 12, 23, 52, 868600), verbose_name='项目终止时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='start_time',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2018, 3, 21, 12, 24, 5, 668345), verbose_name='项目开始时间'),
            preserve_default=False,
        ),
    ]
