# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-12 19:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20180312_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='任务参与人员'),
        ),
    ]
