# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-13 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20180312_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_task', to='group.Group', verbose_name='任务参与团队'),
        ),
    ]
