# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-21 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20180321_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persontask',
            name='status',
            field=models.CharField(choices=[('executing', '执行'), ('acceptance', '验收'), ('release', '发布'), ('suspend', '滞后')], default='executing', max_length=15),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('executing', '执行'), ('acceptance', '验收'), ('release', '发布'), ('suspend', '滞后')], default='executing', max_length=15),
        ),
    ]
