# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-13 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20180313_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='start_time',
            field=models.DateField(blank=True, null=True, verbose_name='项目开始时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='create_time',
            field=models.DateField(auto_now_add=True, verbose_name='项目创建时间'),
        ),
    ]
