# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-27 15:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20180321_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='persontask',
            name='edit_time',
            field=models.DateField(auto_now=True, default=datetime.datetime(2018, 3, 27, 15, 57, 49, 133692), verbose_name='最后修改时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='edit_time',
            field=models.DateField(auto_now=True, default=datetime.datetime(2018, 3, 27, 15, 58, 0, 637767), verbose_name='最后修改时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='edit_time',
            field=models.DateField(auto_now=True, default=datetime.datetime(2018, 3, 27, 15, 58, 8, 525380), verbose_name='最后修改时间'),
            preserve_default=False,
        ),
    ]
