# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-14 14:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0007_auto_20180314_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psp', models.IntegerField(default=0, verbose_name='个人sp值')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='任务完成人')),
            ],
            options={
                'verbose_name': '个人任务',
                'verbose_name_plural': '个人任务',
            },
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': '小组任务', 'verbose_name_plural': '小组任务'},
        ),
        migrations.AlterField(
            model_name='task',
            name='gsp',
            field=models.IntegerField(default=0, verbose_name='小组SP值'),
        ),
    ]
