# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-14 14:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20180314_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='members',
        ),
        migrations.AddField(
            model_name='persontask',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Task', verbose_name='小组任务'),
        ),
        migrations.AlterField(
            model_name='persontask',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='任务完成人'),
        ),
    ]
