# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-27 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20180327_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='edit_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_time',
            field=models.DateField(auto_now_add=True, verbose_name='实际终止时间'),
        ),
    ]
