# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-14 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20180314_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persontask',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_task', to='project.Task', verbose_name='小组任务'),
        ),
    ]
