# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-14 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20180314_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='impression',
            field=models.FloatField(default=0, verbose_name='项目成效'),
        ),
    ]
