# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-14 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20180314_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='acceptance_medium_bug',
            field=models.IntegerField(default=0, verbose_name='验收阶段中级缺陷'),
        ),
        migrations.AlterField(
            model_name='project',
            name='acceptance_serious_bug',
            field=models.IntegerField(default=0, verbose_name='验收阶段严重缺陷'),
        ),
        migrations.AlterField(
            model_name='project',
            name='acceptance_slight_bug',
            field=models.IntegerField(default=0, verbose_name='验收阶段低级缺陷'),
        ),
        migrations.AlterField(
            model_name='project',
            name='release_medium_bug',
            field=models.IntegerField(default=0, verbose_name='发布阶段中级缺陷'),
        ),
        migrations.AlterField(
            model_name='project',
            name='release_serious_bug',
            field=models.IntegerField(default=0, verbose_name='发布阶段严重缺陷'),
        ),
        migrations.AlterField(
            model_name='project',
            name='release_slight_bug',
            field=models.IntegerField(default=0, verbose_name='发布阶段低级缺陷'),
        ),
    ]
